name: Publish to npm
#This runs every time something is pushed to master branch, however npm 
# doesnt allow publishing one version more than once, therefore to get a new version published, the version number has to be changed in package.json
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm install

    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
